language: java

install: true

before_install:
- nvm install
before_script:
- npm install
- yarn global add @vue/cli
- npm install -g @vue/cli-service-global

jdk:
- oraclejdk11
script:
- ./gradlew clean test build -Pfrontend