language: java

sudo: enabled

install: true

before_install:
- nvm install 12
before_script:
- npm install
- yarn global add @vue/cli
- echo $PATH
- export PATH=$PATH:frontend/node_modules/.bin
- echo $PATH
- pwd
jdk:
- oraclejdk11
script:
- ./gradlew clean test build -Pfrontend