language: java

install: true

services:
- docker

before_install:
- nvm install 12

before_script:
- cd frontend
- npm install
- npm install -g @vue/cli
- cd ..

jdk:
- oraclejdk11

script:
- ./gradlew clean test build -Pfrontend
- docker build -t portfolio-manager .

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "portfolio-manager"
  env: "preview"
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  bucket-name: "$BUCKET_NAME"
  path: "portfolio-manager"
  on:
    branch: ci-test
  skip_cleanup: true