language: java

sudo: enabled

install: true

before_install:
- nvm install 12
before_script:
- cd frontend
- npm install
- npm install -g @vue/cli
- echo $PATH
- export PATH="$(yarn global bin):$PATH"
- echo $PATH
- ls -ltra /home/travis/.yarn/bin
- pwd
- cd ..
- pwd
jdk:
- oraclejdk11
script:
- ./gradlew clean test build -Pfrontend