language: java

sudo: enabled

install: true

before_install:
- nvm install 12
before_script:
- npm install
- yarn global add @vue/cli
- export PATH=$PATH:~./frontend/node_modules/.bin
- pwd
- cp ~/frontend/node_modules/.bin/vue-cli-service /bin/sh
jdk:
- oraclejdk11
script:
- ./gradlew clean test build -Pfrontend